site_name: Challenge

repo_url: https://github.com/elwuapo/challenge
dev_addr: 127.0.0.1:9000

theme:
  name: material

markdown_extensions:
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
