# Generated by Django 4.2.4 on 2023-08-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('punch_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.person')),
            ],
        ),
    ]
