# Generated by Django 4.2.4 on 2023-08-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_person_email_alter_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punch',
            old_name='person_id',
            new_name='person',
        ),
    ]
