# Generated by Django 4.2.4 on 2023-08-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_report_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='filename',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='report',
            name='path',
            field=models.CharField(default='', max_length=256),
        ),
    ]
